### ISSUE TITLE
Remove #[abstraction] from the macros

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/openzeppelin-pallet-abstractions#45]
**🧐 Motivation**
Is is [used](https://github.com/OpenZeppelin/openzeppelin-pallet-abstractions/blob/main/procedural/src/construct_runtime.rs#L18) mostly as a marker to know wether the code is an abstraction or a single pallet, but this should be able to be inferred from the type as well

**Comment by ozgunozerk** [comment]
relevant comment from the PR: https://github.com/OpenZeppelin/openzeppelin-pallet-abstractions/pull/17#discussion_r1801060252
